class_name HeroDef
## Sankarien staattiset määrittelyt: nimet, roolit, tilastot, kyvyt ja värit.
## Sankariluokat lukevat cooldownit ja perustilastot täältä, jotta
## käyttöliittymä ja pelilogiikka pysyvät aina samassa linjassa.

const ORDER := [
	"bastion", "ember", "luma", "blink", "bramble", "quill",
	"boulder", "volt", "maestro", "shade", "tide", "scout",
]

const HEROES := {
	"bastion": {
		"name": "Bastion",
		"role": "Tankki",
		"difficulty": 1,
		"hp": 280.0,
		"speed": 295.0,
		"ratings": {"kesto": 5, "liike": 2, "vahinko": 2, "tuki": 4},
		"weapon": "Kilpi ja nuija",
		"desc": "Rintaman kallio. Suojaa joukkuetta edestä ja pitää linjan.",
		"color": Color("86ccd9"),
		"color_b": Color("2e5f74"),
		"abilities": {
			"basic": {"name": "Nuijan heilautus", "desc": "Leveä pyyhkäisy eteen.", "cd": 0.6},
			"a1": {"name": "Kilpivalli", "desc": "Torjuu edestä tulevat osumat 2,6 s ajan.", "cd": 9.0},
			"a2": {"name": "Maanjäristys", "desc": "Maahan isku: vahinkoa, työntö ja hidastus ympärillä.", "cd": 7.5},
			"dodge": {"name": "Rynnäkkö", "desc": "Raskas syöksy, joka tönäisee vihollisia.", "cd": 5.0},
			"ult": {"name": "Linnake", "desc": "Suuri kupoli, joka torjuu vihollisammukset ja kilpiää liittolaiset.", "cd": 0.0},
		},
	},
	"ember": {
		"name": "Ember",
		"role": "Mage",
		"difficulty": 2,
		"hp": 170.0,
		"speed": 320.0,
		"ratings": {"kesto": 2, "liike": 3, "vahinko": 5, "tuki": 1},
		"weapon": "Tulilyhty",
		"desc": "Alueiden hallitsija. Sytyttää kentän palamaan ja pakottaa liikkeelle.",
		"color": Color("ff8a4a"),
		"color_b": Color("b33b17"),
		"abilities": {
			"basic": {"name": "Tulipallo", "desc": "Suora ammus, joka sytyttää jälkipolton.", "cd": 0.55},
			"a1": {"name": "Liekkilammikko", "desc": "Heittää palavan alueen, joka polttaa vihollisia.", "cd": 8.0},
			"a2": {"name": "Lämpöaalto", "desc": "Viuhkapurkaus eteen: vahinko, työntö ja jälkipoltto.", "cd": 7.0},
			"dodge": {"name": "Kipinäliuku", "desc": "Nopea liuku, joka jättää kipinäjäljen.", "cd": 4.0},
			"ult": {"name": "Tulimyrsky", "desc": "Laajeneva liekkirengas, joka jättää lammikoita.", "cd": 0.0},
		},
	},
	"luma": {
		"name": "Luma",
		"role": "Tuki",
		"difficulty": 2,
		"hp": 200.0,
		"speed": 325.0,
		"ratings": {"kesto": 3, "liike": 3, "vahinko": 2, "tuki": 5},
		"weapon": "Valosauva",
		"desc": "Joukkueen sydän. Parantaa, suojaa ja pitää kaikki pelissä.",
		"color": Color("ffe9a8"),
		"color_b": Color("d9a13f"),
		"abilities": {
			"basic": {"name": "Valopulssi", "desc": "Ammus, joka vahingoittaa vihollisia ja parantaa liittolaiset läpi mennessään.", "cd": 0.5},
			"a1": {"name": "Hoitokehä", "desc": "Parantava purkaus Luman ympärillä.", "cd": 8.0},
			"a2": {"name": "Suojasäde", "desc": "Suojakilpi eniten kärsineelle liittolaiselle.", "cd": 7.0},
			"dodge": {"name": "Pyrähdys", "desc": "Kevyt ja nopea väistö, joka antaa vauhtia.", "cd": 3.5},
			"ult": {"name": "Valokenttä", "desc": "Suuri alue, joka parantaa ja nopeuttaa liittolaisia.", "cd": 0.0},
		},
	},
	"blink": {
		"name": "Blink",
		"role": "Assassin",
		"difficulty": 3,
		"hp": 160.0,
		"speed": 360.0,
		"ratings": {"kesto": 2, "liike": 5, "vahinko": 4, "tuki": 1},
		"weapon": "Kaksi valomiekkaa",
		"desc": "Välähdys pimeässä. Iskee, katoaa ja iskee taas.",
		"color": Color("b48aff"),
		"color_b": Color("5b2f9e"),
		"abilities": {
			"basic": {"name": "Valoviilto", "desc": "Nopea kaksoisviilto. Selkäänisku tekee 50 % lisää.", "cd": 0.4},
			"a1": {"name": "Teleportti", "desc": "Siirtyy hetkessä tähtäyksen suuntaan.", "cd": 6.0},
			"a2": {"name": "Valoviuhka", "desc": "Heittää kolme valoterää viuhkana.", "cd": 7.0},
			"dodge": {"name": "Sivuaskel", "desc": "Salamannopea väistöliike.", "cd": 3.0},
			"ult": {"name": "Varjotanssi", "desc": "Iskee sarjan teleportteja lähivihollisten läpi.", "cd": 0.0},
		},
	},
	"bramble": {
		"name": "Bramble",
		"role": "Fighter",
		"difficulty": 2,
		"hp": 230.0,
		"speed": 310.0,
		"ratings": {"kesto": 4, "liike": 3, "vahinko": 3, "tuki": 2},
		"weapon": "Köynnösruoska",
		"desc": "Piikikäs lähitaistelija, joka sitoo viholliset paikoilleen.",
		"color": Color("7ed957"),
		"color_b": Color("2f7a33"),
		"abilities": {
			"basic": {"name": "Ruoskanisku", "desc": "Kaareva pyyhkäisy, joka imee elinvoimaa osumista.", "cd": 0.55},
			"a1": {"name": "Juurisidonta", "desc": "Köynnös, joka juurruttaa ensimmäisen osuman paikoilleen.", "cd": 8.0},
			"a2": {"name": "Piikkipyörre", "desc": "Piikit sinkoutuvat ympärille ja jättävät hidastavan piikkialueen.", "cd": 7.5},
			"dodge": {"name": "Köynnösheitto", "desc": "Vetäisee itsensä ruoskalla eteenpäin.", "cd": 4.0},
			"ult": {"name": "Piikkipuutarha", "desc": "Suuri alue, joka juurruttaa, hidastaa ja pistelee vihollisia.", "cd": 0.0},
		},
	},
	"quill": {
		"name": "Quill",
		"role": "Ranger",
		"difficulty": 2,
		"hp": 175.0,
		"speed": 330.0,
		"ratings": {"kesto": 2, "liike": 3, "vahinko": 4, "tuki": 2},
		"weapon": "Jousi",
		"desc": "Tarkka-ampuja. Ladattu nuoli palkitsee kärsivällisen.",
		"color": Color("5fd0a0"),
		"color_b": Color("1f6e52"),
		"abilities": {
			"basic": {"name": "Nuoli", "desc": "Pidä pohjassa ladataksesi. Paikallaan lataa nopeammin; täysi lataus lävistää.", "cd": 0.5},
			"a1": {"name": "Tarkkuuslaukaus", "desc": "Pitkä, nopea ja lävistävä erikoisnuoli.", "cd": 7.0},
			"a2": {"name": "Nuolisade", "desc": "Nuolia sataa valitulle alueelle hetken päästä.", "cd": 8.0},
			"dodge": {"name": "Kuperkeikka", "desc": "Nopea kieräys, joka lataa jousen heti valmiiksi.", "cd": 3.5},
			"ult": {"name": "Myrskysarja", "desc": "Ampuu nopean sarjan nuolia tähtäyksen mukaan.", "cd": 0.0},
		},
	},
	"boulder": {
		"name": "Boulder",
		"role": "Tankki",
		"difficulty": 1,
		"hp": 300.0,
		"speed": 285.0,
		"ratings": {"kesto": 5, "liike": 1, "vahinko": 3, "tuki": 3},
		"weapon": "Kivihansikkaat",
		"desc": "Kävelevä kallio. Rakentaa muureja ja jyrää esteet.",
		"color": Color("9aa3ad"),
		"color_b": Color("4f5a66"),
		"abilities": {
			"basic": {"name": "Murskaava isku", "desc": "Raskas lyönti, joka tönäisee kunnolla.", "cd": 0.7},
			"a1": {"name": "Kivimuuri", "desc": "Nostaa väliaikaisen muurin, joka estää liikkeen ja ammukset.", "cd": 10.0},
			"a2": {"name": "Tömistys", "desc": "Isku maahan: työntää kaikki lähellä olevat kauas.", "cd": 8.0},
			"dodge": {"name": "Jyräys", "desc": "Raskas loikka eteenpäin.", "cd": 5.0},
			"ult": {"name": "Vyöry", "desc": "Vyöryy eteenpäin kaataen kaikki tieltään.", "cd": 0.0},
		},
	},
	"volt": {
		"name": "Volt",
		"role": "Mage",
		"difficulty": 2,
		"hp": 165.0,
		"speed": 325.0,
		"ratings": {"kesto": 2, "liike": 3, "vahinko": 5, "tuki": 1},
		"weapon": "Sähkökelat",
		"desc": "Elävä ukkospilvi. Salamat hyppivät vihollisesta toiseen.",
		"color": Color("ffe14a"),
		"color_b": Color("8f7600"),
		"abilities": {
			"basic": {"name": "Kipinä", "desc": "Sähköammus, joka hyppää lähimpään toiseen viholliseen.", "cd": 0.55},
			"a1": {"name": "Ketjusalama", "desc": "Salama, joka ketjuttaa jopa kolmeen viholliseen ja hidastaa.", "cd": 7.0},
			"a2": {"name": "Sähkökenttä", "desc": "Rätisevä alue, joka hidastaa ja tekee vahinkoa.", "cd": 8.0},
			"dodge": {"name": "Kipinähyppy", "desc": "Salamannopea siirtymä.", "cd": 4.0},
			"ult": {"name": "Ukkosmyrsky", "desc": "Salamat iskevät lähivihollisiin sarjana ja tainnuttavat.", "cd": 0.0},
		},
	},
	"maestro": {
		"name": "Maestro",
		"role": "Tuki",
		"difficulty": 2,
		"hp": 195.0,
		"speed": 320.0,
		"ratings": {"kesto": 3, "liike": 3, "vahinko": 2, "tuki": 5},
		"weapon": "Ääniaaltoheitin",
		"desc": "Rytmin mestari. Kiihdyttää joukkueen täyteen vauhtiin.",
		"color": Color("ff6bd0"),
		"color_b": Color("99307d"),
		"abilities": {
			"basic": {"name": "Ääniaalto", "desc": "Työntävä ääniammus.", "cd": 0.5},
			"a1": {"name": "Kiihdytysriffi", "desc": "Lähiliittolaiset saavat vauhtia ja suojakilven.", "cd": 8.0},
			"a2": {"name": "Basso-isku", "desc": "Bassoaalto eteen: työntö ja lyhyt tainnutus.", "cd": 8.0},
			"dodge": {"name": "Tahdinvaihto", "desc": "Nopea sivuliuku.", "cd": 3.5},
			"ult": {"name": "Crescendo", "desc": "Suuri alue: liittolaiset paranevat ja kiihtyvät, viholliset hidastuvat.", "cd": 0.0},
		},
	},
	"shade": {
		"name": "Shade",
		"role": "Assassin",
		"difficulty": 3,
		"hp": 165.0,
		"speed": 350.0,
		"ratings": {"kesto": 2, "liike": 5, "vahinko": 4, "tuki": 1},
		"weapon": "Varjokiekot",
		"desc": "Savuun katoava kiusankappale. Jättää jälkeensä vain harhakuvan.",
		"color": Color("9089b8"),
		"color_b": Color("3f3a63"),
		"abilities": {
			"basic": {"name": "Varjokiekko", "desc": "Nopea pyörivä heittokiekko.", "cd": 0.45},
			"a1": {"name": "Naamioituminen", "desc": "Jättää harhakuvan, häipyy savuun ja saa vauhtia.", "cd": 8.0},
			"a2": {"name": "Palaava kiekko", "desc": "Kiekko lävistää useita ja palaa takaisin.", "cd": 7.0},
			"dodge": {"name": "Varjoaskel", "desc": "Nopea väistö, joka lataa ultimatea.", "cd": 3.0},
			"ult": {"name": "Varjoisku", "desc": "Hetken salamannopea; iskut tehostuvat 60 %.", "cd": 0.0},
		},
	},
	"tide": {
		"name": "Tide",
		"role": "Fighter",
		"difficulty": 2,
		"hp": 220.0,
		"speed": 315.0,
		"ratings": {"kesto": 4, "liike": 4, "vahinko": 3, "tuki": 2},
		"weapon": "Vesikeihäs",
		"desc": "Virtaava taistelija. Liukuu vesivanoja pitkin taisteluun.",
		"color": Color("4ad4ff"),
		"color_b": Color("176d94"),
		"abilities": {
			"basic": {"name": "Keihäspisto", "desc": "Pitkä ja kapea pisto eteen.", "cd": 0.55},
			"a1": {"name": "Vesivana", "desc": "Syöksy, joka jättää liittolaisia kiihdyttävän vanan.", "cd": 7.0},
			"a2": {"name": "Aalto", "desc": "Työntävä vesiaalto eteen, joka hidastaa.", "cd": 7.5},
			"dodge": {"name": "Virtaliuku", "desc": "Liukas väistö, joka antaa vauhtia.", "cd": 4.0},
			"ult": {"name": "Hyökyaalto", "desc": "Valtava laajeneva aalto, joka lakaisee ja hidastaa viholliset.", "cd": 0.0},
		},
	},
	"scout": {
		"name": "Scout",
		"role": "Ranger",
		"difficulty": 2,
		"hp": 180.0,
		"speed": 330.0,
		"ratings": {"kesto": 2, "liike": 3, "vahinko": 3, "tuki": 4},
		"weapon": "Vaahtopallokivääri",
		"desc": "Joukkueen silmät. Merkityt viholliset ottavat lisävahinkoa kaikilta.",
		"color": Color("c9d16b"),
		"color_b": Color("6b7a2f"),
		"abilities": {
			"basic": {"name": "Vaahtopurske", "desc": "Kolmen pallon nopea sarja.", "cd": 0.65},
			"a1": {"name": "Merkkipanos", "desc": "Osuma merkitsee kohteen: se ottaa lisävahinkoa.", "cd": 7.0},
			"a2": {"name": "Tainnutuspallo", "desc": "Tahmea pallo, joka tainnuttaa hetkeksi.", "cd": 9.0},
			"dodge": {"name": "Kierähdys", "desc": "Nopea rullaus, joka lataa kiväärin.", "cd": 3.5},
			"ult": {"name": "Merkkisade", "desc": "Merkitsee kaikki lähiviholliset ja kiihdyttää joukkueen.", "cd": 0.0},
		},
	},
}


static func get_def(id: String) -> Dictionary:
	return HEROES[id]


static func ability(id: String, slot: String) -> Dictionary:
	return HEROES[id]["abilities"][slot]


static func cooldown(id: String, slot: String) -> float:
	return HEROES[id]["abilities"][slot]["cd"]
