class_name HeroDef
## Sankarien staattiset määrittelyt: nimet, roolit, tilastot, kyvyt ja värit.
## Sankariluokat lukevat cooldownit ja perustilastot täältä, jotta
## käyttöliittymä ja pelilogiikka pysyvät aina samassa linjassa.

const ROLE_JUNGLER := "Jungleri"  # varattu tulevalle neljän jungler-heron ryhmälle

const ORDER := [
	"bastion", "ember", "luma", "blink", "bramble", "quill",
	"boulder", "volt", "maestro", "shade", "tide", "scout",
	"prism", "rift", "titan", "hush", "obsidian", "lance", "salvo",
	"kaira", "vesper", "myria", "torq",
]

const HEROES := {
	"bastion": {
		"name": "Bastion",
		"role": "Tankki",
		"difficulty": 1,
		"hp": 340.0,
		"speed": 295.0,
		"ratings": {"kesto": 5, "liike": 2, "vahinko": 1, "tuki": 4},
		"weapon": "Kilpi ja nuija",
		"desc": "Rintaman kallio. Suojaa joukkuetta edestä ja pitää linjan.",
		"color": Color("86ccd9"),
		"color_b": Color("2e5f74"),
		"abilities": {
			"basic": {"name": "Nuijan heilautus", "desc": "Leveä pyyhkäisy eteen.", "cd": 0.6,
				"tip": "Astu askel eteen ennen heilautusta: leveä kaari osuu koko rykelmään.", "scaling": "Skaalaa: hyökkäysvoima, iskunopeus, kriittinen"},
			"a1": {"name": "Kilpivalli", "desc": "Pidä pohjassa nostaaksesi ison etukilven: vaimentaa Bastionin ottamaa vahinkoa ja torjuu edestä tulevat vihollisammukset — suojaa myös takana olevat liittolaiset. Kuluttaa energiaa.", "cd": 9.0,
				"tip": "Käännä kilpi tulen suuntaan ja seiso liittolaisten edessä — takana olevat suojautuvat samalla.", "scaling": "Skaalaa: kyvyn ranki ja energia; ei kykyvahingosta"},
			"a2": {"name": "Vetoisku", "desc": "Vetää ympäröivät viholliset eteen ja tainnuttaa (ei vahinkoa) — kerää viholliset haltuun kilven eteen.", "cd": 7.5,
				"tip": "Vedä viholliset kilven eteen, älä sivuun: veto on koko joukkueen aloitus.", "scaling": "Skaalaa: kyvyn ranki (tainnutus), jäähdytyksen alennus"},
			"dodge": {"name": "Rynnäkkö", "desc": "Raskas syöksy, joka tönäisee vihollisia.", "cd": 5.0,
				"tip": "Käytä rynnäkkö linjan palauttamiseen, ei pakoon — Bastion voittaa seisomalla.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki"},
			"ult": {"name": "Linnake", "desc": "Suuri kupoli, joka torjuu vihollisammukset ja kilpiää liittolaiset.", "cd": 0.0,
				"tip": "Aseta kupoli aallon eteen: se torjuu ammukset ja ostaa joukkueelle koko taistelun.", "scaling": "Skaalaa: ultin ranki ja hoivasydän (kilpimäärä)"},
		},
	},
	"ember": {
		"name": "Ember",
		"role": "Mage",
		"difficulty": 2,
		"hp": 170.0,
		"speed": 320.0,
		"ratings": {"kesto": 2, "liike": 3, "vahinko": 5, "tuki": 1},
		"weapon": "Tulilyhty",
		"desc": "Alueiden hallitsija. Käyttää manaa — voi spämmätä loitsuja kunnes mana loppuu, sitten se palautuu.",
		"color": Color("ff8a4a"),
		"color_b": Color("b33b17"),
		"abilities": {
			"basic": {"name": "Tulipallo", "desc": "Suora ammus, joka sytyttää jälkipolton.", "cd": 0.55,
				"tip": "Riittää että osut kerran: jälkipoltto tekee lopputyön.", "scaling": "Skaalaa: hyökkäysvoima, iskunopeus"},
			"a1": {"name": "Liekkilammikko", "desc": "Heittää palavan alueen, joka polttaa vihollisia. Pidä R1 pohjassa ja siirrä maalia oikealla tatilla; vapauta heittääksesi.", "cd": 8.0,
				"tip": "Heitä lammikko sinne mihin vihollinen JOUTUU menemään, ei sinne missä se nyt on.", "scaling": "Skaalaa: kykyvahinko (ap), taso, kyvyn ranki"},
			"a2": {"name": "Lämpöaalto", "desc": "Viuhkapurkaus eteen: vahinko, työntö ja jälkipoltto.", "cd": 7.0,
				"tip": "Työntö on yhtä arvokas kuin vahinko: aja kohde ulos suojasta tai sisään omaan lammikkoosi.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki"},
			"dodge": {"name": "Kipinäliuku", "desc": "Nopea liuku, joka jättää kipinäjäljen.", "cd": 4.0,
				"tip": "Liu'u sivuun skillshotin linjalta, älä taaksepäin — mage kuolee suoralla linjalla.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki"},
			"ult": {"name": "Tulimyrsky", "desc": "Laajeneva liekkirengas, joka jättää lammikoita.", "cd": 0.0,
				"tip": "Laukaise rengas keskeltä rykelmää: jäävät lammikot estävät perääntymisen.", "scaling": "Skaalaa: kykyvahinko (ap), ultin ranki"},
		},
	},
	"luma": {
		"name": "Luma",
		"role": "Tuki",
		"difficulty": 2,
		"hp": 200.0,
		"speed": 325.0,
		"ratings": {"kesto": 3, "liike": 3, "vahinko": 2, "tuki": 5},
		"weapon": "Valosauva",
		"desc": "Joukkueen sydän. Käyttää manaa — voi ketjuttaa hoitoja ja kilpiä kunnes mana loppuu, sitten se palautuu.",
		"color": Color("ffe9a8"),
		"color_b": Color("d9a13f"),
		"abilities": {
			"basic": {"name": "Valopulssi", "desc": "Ammus, joka vahingoittaa vihollisia ja parantaa liittolaiset läpi mennessään.", "cd": 0.5,
				"tip": "Ammu liittolaisen LÄPI viholliseen: sama laukaus parantaa ja vahingoittaa.", "scaling": "Skaalaa: hyökkäysvoima; parannus kyvyn rankista"},
			"a1": {"name": "Hoitokehä", "desc": "Parantava purkaus Luman ympärillä.", "cd": 8.0,
				"tip": "Odota että kaksi liittolaista on säteellä — kehä on tuhlausta yhdelle.", "scaling": "Skaalaa: kyvyn ranki ja hoivasydän; ei kykyvahingosta"},
			"a2": {"name": "Suojasäde", "desc": "Suojakilpi eniten kärsineelle liittolaiselle.", "cd": 7.0,
				"tip": "Kilpi ennen osumaa, ei sen jälkeen: ennakoi vihollisen aloitus.", "scaling": "Skaalaa: kyvyn ranki ja hoivasydän"},
			"dodge": {"name": "Pyrähdys", "desc": "Kevyt ja nopea väistö, joka antaa vauhtia.", "cd": 3.5,
				"tip": "Pyrähdys on asemointiväline: pysy kantajan takana, älä edessä.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki"},
			"ult": {"name": "Valokenttä", "desc": "Suuri alue, joka parantaa ja nopeuttaa liittolaisia.", "cd": 0.0,
				"tip": "Aseta kenttä sinne mihin joukkue JÄÄ seisomaan, ei sinne mistä se juuri lähti.", "scaling": "Skaalaa: ultin ranki ja hoivasydän"},
		},
	},
	"blink": {
		"name": "Blink",
		"role": "Assassin",
		"difficulty": 3,
		"hp": 148.0,
		"speed": 360.0,
		"ratings": {"kesto": 1, "liike": 5, "vahinko": 5, "tuki": 1},
		"weapon": "Kaksi valomiekkaa",
		"desc": "Välähdysduellisti. Menee sisään ja tulee ULOS: Välähdys jättää kaiun, jolle voi palata. Vahinko tulee kahdesta ikkunasta — kolmen iskun rytmistä ja Jälkiterän lopetuksesta.",
		"color": Color("b48aff"),
		"color_b": Color("5b2f9e"),
		"abilities": {
			"basic": {"name": "Valoviilto", "desc": "Nopea valoviilto. Kolme peräkkäistä OSUMAA 1,5 sekunnin sisällä laukaisee Kaksoisviillon: 2,3x vahinko, pidempi ulottuvuus ja hyvitys Välähdyksen jäähdytyksestä. Huti nollaa rytmin.", "cd": 0.4,
				"tip": "Pysy kohteessa kolme iskua: kolmas on Kaksoisviilto. Huti nollaa rytmin.", "scaling": "Skaalaa: hyökkäysvoima, kriittinen (tehostettu isku), iskunopeus"},
			"a1": {"name": "Välähdys ja kaiku", "desc": "Pidä R1 ja suuntaa: teleportti, joka iskee saapumisessa ja jättää lähtöpaikkaan kaiun 3,5 sekunniksi. Toinen painallus palaa kaiulle uudella iskulla — tämä on pakotie. Kaato lataa kyvyn heti uudelleen.", "cd": 8.0,
				"tip": "Välähdä sisään ja PALAA kaiulle ennen kuin ikkuna sulkeutuu — kaiku on ainoa pakotiesi.", "scaling": "Skaalaa: hyökkäysvoima (kova), kykyvahinko, kyvyn ranki"},
			"a2": {"name": "Valoviuhka", "desc": "Kolme valoterää viuhkana. Ensimmäinen sankariosuma avaa 0,45 sekunnin ikkunan: paina L1 uudelleen ja Jälkiterä hakeutuu kohteeseen tehden sitä kovempaa mitä vähemmän kohteella on elämää jäljellä.", "cd": 5.0,
				"tip": "Kun viuhka osuu, paina L1 heti uudelleen: Jälkiterä teloittaa haavoittuneen.", "scaling": "Skaalaa: hyökkäysvoima (kova), kohteen puuttuva elämä, kykyvahinko"},
			"dodge": {"name": "Sivuaskel", "desc": "Salamannopea väistöliike.", "cd": 3.0,
				"tip": "Säästä sivuaskel skillshotin väistämiseen — Välähdys hoitaa matkanteon.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki"},
			"ult": {"name": "Valotanssi", "desc": "Sarja selkäänteleportteja haavoittuneimpiin vihollisiin. Jokainen isku teloittaa puuttuvan elämän mukaan ja jokainen kaato pidentää tanssia. Lopuksi Välähdys on heti valmis.", "cd": 0.0,
				"tip": "Avaa tanssi vasta kun joku on jo haavoittunut: jokainen kaato pidentää sitä.", "scaling": "Skaalaa: hyökkäysvoima (kova), kohteiden puuttuva elämä, ultin ranki"},
		},
	},
	"bramble": {
		"name": "Bramble",
		"role": "Fighter",
		"difficulty": 2,
		"hp": 250.0,
		"speed": 310.0,
		"ratings": {"kesto": 4, "liike": 3, "vahinko": 3, "tuki": 2},
		"weapon": "Köynnösruoska",
		"desc": "Piikikäs lähitaistelija. Kerää raivoa taistelusta ja purkaa sen kykyihin.",
		"color": Color("7ed957"),
		"color_b": Color("2f7a33"),
		"abilities": {
			"basic": {"name": "Ruoskanisku", "desc": "Kaareva pyyhkäisy, joka imee elinvoimaa osumista.", "cd": 0.55,
				"tip": "Osu useaan kerralla: elinvoiman imu kasvaa osumien määrällä.", "scaling": "Skaalaa: hyökkäysvoima, iskunopeus, elinvoiman imu"},
			"a1": {"name": "Juurisidonta", "desc": "Köynnös, joka juurruttaa ensimmäisen osuman paikoilleen. Tähtää pitämällä nappia pohjassa.", "cd": 8.0,
				"tip": "Juurruta pakeneva, älä kiinni oleva — sidonta on kiinniottoväline.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki (juurrutus)"},
			"a2": {"name": "Piikkipyörre", "desc": "Piikit sinkoutuvat ympärille ja jättävät hidastavan piikkialueen.", "cd": 7.5,
				"tip": "Purista pyörre kun kaksi vihollista on kiinni: piikkialue estää perääntymisen.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki, raivo"},
			"dodge": {"name": "Köynnösheitto", "desc": "Vetäisee itsensä ruoskalla eteenpäin.", "cd": 4.0,
				"tip": "Heitto on kiinniotto: vedä itsesi karkaavan perään, älä pois taistelusta.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki"},
			"ult": {"name": "Piikkipuutarha", "desc": "Varoituksen jälkeen maasta kasvaa suuri juuripuutarha, joka juurruttaa, hidastaa ja pistelee vihollisia kuuden sekunnin ajan.", "cd": 0.0,
				"tip": "Puutarha telegrafoidaan — aseta se pakoreitille, ei kohteen nykyiseen paikkaan.", "scaling": "Skaalaa: kykyvahinko (ap), ultin ranki"},
		},
	},
	"quill": {
		"name": "Quill",
		"role": "Ranger",
		"difficulty": 2,
		"hp": 175.0,
		"speed": 330.0,
		"ratings": {"kesto": 2, "liike": 3, "vahinko": 4, "tuki": 2},
		"weapon": "Jousi",
		"desc": "Tarkka-ampuja. Osumat lataavat energiaa, joka ruokkii erikoislaukauksia — tarkkuus palkitaan.",
		"color": Color("5fd0a0"),
		"color_b": Color("1f6e52"),
		"abilities": {
			"basic": {"name": "Nuoli", "desc": "Pidä pohjassa ladataksesi. Paikallaan lataa nopeammin; täysi lataus lävistää.", "cd": 0.5,
				"tip": "Seiso paikallaan hetki: lataus on 40 % nopeampi ja täysi nuoli lävistää.", "scaling": "Skaalaa: hyökkäysvoima, kriittinen, iskunopeus, latausaste"},
			"a1": {"name": "Väistösyöksy", "desc": "Loikkaa taaksepäin ja jättää lähtöpaikkaan piikkialueen, joka hidastaa ja vahingoittaa siihen astuvia.", "cd": 7.0,
				"tip": "Loikkaa kohti uhkaa: syöksy vie taaksepäin ja jättää piikit siihen mistä lähdit.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki"},
			"a2": {"name": "Nuolisade", "desc": "Nuolia sataa valitulle alueelle hetken päästä. Pidä L1 pohjassa ja siirrä maalia oikealla tatilla.", "cd": 8.0,
				"tip": "Ennakoi viive: tähtää sinne missä kohde on sekunnin päästä.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki"},
			"dodge": {"name": "Kuperkeikka", "desc": "Nopea kieräys, joka lataa jousen heti valmiiksi.", "cd": 3.5,
				"tip": "Kuperkeikka lataa jousen heti — kierähdä latauksen sijaan kun aika on tiukalla.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki"},
			"ult": {"name": "Läpäisynuoli", "desc": "Pidä L2 pohjassa tähdätäksesi leveän osumakäytävän. Vapautus varoittaa hetken ja ampuu koko kartan läpäisevän supernuolen.", "cd": 0.0,
				"tip": "Odota että kaksi vihollista on samalla linjalla: nuoli lävistää koko kartan.", "scaling": "Skaalaa: kykyvahinko (ap), ultin ranki"},
		},
	},
	"boulder": {
		"name": "Boulder",
		"role": "Tankki",
		"difficulty": 1,
		"hp": 360.0,
		"speed": 285.0,
		"ratings": {"kesto": 5, "liike": 1, "vahinko": 2, "tuki": 3},
		"weapon": "Kivihansikkaat",
		"desc": "Kävelevä kallio. Hallitsee aluetta kestävillä kivimuureilla ja piikkikartioilla; kerää raivoa taistelusta.",
		"color": Color("9aa3ad"),
		"color_b": Color("4f5a66"),
		"abilities": {
			"basic": {"name": "Murskaava isku", "desc": "Raskas lyönti, joka tönäisee kunnolla.", "cd": 0.7,
				"tip": "Työnnä vihollinen omaa muuria vasten: tönäisy on Boulderin kontrolli.", "scaling": "Skaalaa: hyökkäysvoima, iskunopeus"},
			"a1": {"name": "Kivimuuri", "desc": "Nostaa kestävän muurin (oma kesto-hp), joka estää liikkeen ja ammukset. 3 latausta — voi pystyttää vaikka kaikki heti, lataukset palautuvat hitaasti. Tähtää pitämällä nappia pohjassa.", "cd": 0.3,
				"tip": "Katkaise pakoreitti, älä rakenna suojaa itsellesi — muuri on ansa.", "scaling": "Skaalaa: kyvyn ranki (muurin kesto); 3 latausta"},
			"a2": {"name": "Piikkikartio", "desc": "Iskee neljä piikkiaaltoa eteenpäin kartioon: aallot levenevät, työntävät kohteet poispäin ja juurruttavat hetkeksi. Kuluttaa raivoa.", "cd": 5.0,
				"tip": "Kartio levenee matkalla: ammu kauempaa niin se kattaa koko pakosuunnan.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki, raivo"},
			"dodge": {"name": "Jyräys", "desc": "Raskas loikka eteenpäin.", "cd": 5.0,
				"tip": "Jyräys on aloitus: sillä pääsee muurin taakse pudonneen vihollisen kimppuun.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki"},
			"ult": {"name": "Vyöry", "desc": "Pidä L2 tähdätäksesi leveän jyräyslinjan. Boulder vyöryy seinien läpi, kaataa viholliset, jättää kivijäljen ja päättää isoon maaiskuun.", "cd": 0.0,
				"tip": "Tähtää linja seinien läpi — Vyöry kulkee niistä ja kaataa kaiken matkalla.", "scaling": "Skaalaa: kykyvahinko (ap), ultin ranki"},
		},
	},
	"volt": {
		"name": "Volt",
		"role": "Mage",
		"difficulty": 2,
		"hp": 160.0,
		"speed": 325.0,
		"ratings": {"kesto": 2, "liike": 3, "vahinko": 5, "tuki": 1},
		"weapon": "Sähkökelat",
		"desc": "Elävä ukkospilvi. Käyttää manaa — salamoi tiheään kunnes mana loppuu.",
		"color": Color("ffe14a"),
		"color_b": Color("8f7600"),
		"abilities": {
			"basic": {"name": "Kipinä", "desc": "Sähköammus, joka hyppää lähimpään toiseen viholliseen.", "cd": 0.55,
				"tip": "Ammu lähimpään: kipinä hyppää itse seuraavaan, joten rykelmä tuplaa vahingon.", "scaling": "Skaalaa: hyökkäysvoima, iskunopeus"},
			"a1": {"name": "Ketjusalama", "desc": "Salama, joka ketjuttaa jopa kolmeen viholliseen ja hidastaa.", "cd": 7.0,
				"tip": "Aloita reunimmaisesta vihollisesta: ketju kulkee silloin koko rykelmän läpi.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki"},
			"a2": {"name": "Sähkökenttä", "desc": "Rätisevä alue, joka hidastaa ja tekee vahinkoa. Pidä L1 pohjassa ja siirrä maalia oikealla tatilla.", "cd": 8.0,
				"tip": "Kenttä on aluekielto: aseta se objektiivin päälle, älä liikkuvan kohteen perään.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki"},
			"dodge": {"name": "Kipinähyppy", "desc": "Salamannopea siirtymä.", "cd": 4.0,
				"tip": "Hyppy on lyhyt: käytä se kulman taakse näkösuojaan, ei pitkään pakoon.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki"},
			"ult": {"name": "Ukkosmyrsky", "desc": "Pidä L2 ja siirrä myrskykeskusta oikealla tatilla. Seitsemän väistettävää salamaa iskee alueelle sarjana.", "cd": 0.0,
				"tip": "Salamat iskevät sarjana — sijoita keskus sinne mistä vihollisen on pakko kulkea.", "scaling": "Skaalaa: kykyvahinko (ap), ultin ranki"},
		},
	},
	"maestro": {
		"name": "Maestro",
		"role": "Tuki",
		"difficulty": 2,
		"hp": 195.0,
		"speed": 320.0,
		"ratings": {"kesto": 3, "liike": 3, "vahinko": 2, "tuki": 5},
		"weapon": "Ääniaaltoheitin",
		"desc": "Rytmin mestari. Käyttää manaa — kiihdyttää ja suojaa joukkuetta tiuhaan kunnes mana loppuu, sitten se palautuu.",
		"color": Color("ff6bd0"),
		"color_b": Color("99307d"),
		"abilities": {
			"basic": {"name": "Ääniaalto", "desc": "Työntävä ääniammus.", "cd": 0.5,
				"tip": "Työnnä vihollinen pois liittolaisen päältä: aalto on pelastusväline.", "scaling": "Skaalaa: hyökkäysvoima, iskunopeus"},
			"a1": {"name": "Kiihdytysriffi", "desc": "Lähiliittolaiset saavat vauhtia ja suojakilven.", "cd": 8.0,
				"tip": "Riffi ennen sisäänmenoa, ei sen jälkeen: vauhti ja kilpi ovat aloituksen työkaluja.", "scaling": "Skaalaa: kyvyn ranki ja hoivasydän"},
			"a2": {"name": "Basso-isku", "desc": "Bassoaalto eteen: työntö ja lyhyt tainnutus.", "cd": 8.0,
				"tip": "Tainnutus on lyhyt — käytä se katkaisemaan vihollisen kanavointi.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki (tainnutus)"},
			"dodge": {"name": "Tahdinvaihto", "desc": "Nopea sivuliuku.", "cd": 3.5,
				"tip": "Sivuliuku pitää sinut liittolaisten kantamalla; tuki kuolee eksyessään.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki"},
			"ult": {"name": "Crescendo", "desc": "Suuri alue: liittolaiset paranevat ja kiihtyvät, viholliset hidastuvat.", "cd": 0.0,
				"tip": "Laukaise Crescendo kun molemmat joukkueet ovat kasassa: se parantaa ja hidastaa yhtä aikaa.", "scaling": "Skaalaa: ultin ranki ja hoivasydän"},
		},
	},
	"shade": {
		"name": "Shade",
		"role": "Assassin",
		"difficulty": 3,
		"hp": 152.0,
		"speed": 350.0,
		"ratings": {"kesto": 1, "liike": 5, "vahinko": 5, "tuki": 1},
		"weapon": "Varjot ja shurikenit",
		"desc": "Varjoväijyjä. Yksi silmukka: kerää varjopisteet selän takaa, teloita shurikenin paluuvedolla ja katoa varjoon.",
		"color": Color("9089b8"),
		"color_b": Color("3f3a63"),
		"abilities": {
			"basic": {"name": "Varjokiekko", "desc": "Nopea pyörivä heittokiekko. SELKÄÄNISKU: poispäin katsovaan kohteeseen osuma tekee 60 % lisää ja kerää varjopisteen (enintään 3), joka tehostaa shurikenin paluuvetoa.", "cd": 0.45,
				"tip": "Kierrä kohteen selän taakse: selkäänisku kerää varjopisteet, jotka teloitusveto käyttää.", "scaling": "Skaalaa: hyökkäysvoima, kriittinen, iskunopeus"},
			"a1": {"name": "Varjoloikka", "desc": "Pidä R1 ja suuntaa: loikka iskee saapumisessa, merkitsee osuneet ja jättää lähtöpaikkaan varjon 4 sekunniksi. Toinen painallus palaa varjolle isolla purkauksella ja jättää lyhyen häiveen — tämä on pakotie.", "cd": 9.0,
				"tip": "Loikkaa sisään, iske ja PALAA varjolle ennen ikkunan sulkeutumista — paluu jättää häiveen.", "scaling": "Skaalaa: hyökkäysvoima (kova), kykyvahinko, kyvyn ranki"},
			"a2": {"name": "Paluushuriken", "desc": "Pidä L1 ja heitä iso shuriken; toinen painallus kutsuu sen takaisin. Ulosveto naputtaa, PALUUVETO teloittaa: vahinko kasvaa kohteen puuttuvan elämän ja varjopisteiden mukaan. Koppi lyhentää jäähdytyksen kolmasosaan.", "cd": 6.0,
				"tip": "Kutsu shuriken takaisin vasta kun se on OHITTANUT kohteen: paluuveto teloittaa.", "scaling": "Skaalaa: hyökkäysvoima (kova), kohteen puuttuva elämä, varjopisteet"},
			"dodge": {"name": "Varjoaskel", "desc": "Nopea väistö, joka lataa ultimatea.", "cd": 3.0,
				"tip": "Varjoaskel lataa ultia — käytä sitä myös silloin kun mikään ei uhkaa.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki"},
			"ult": {"name": "Varjoteurastus", "desc": "Shade katoaa savuun ja ilmestyy haavoittuneimman vihollisen selän taakse teloittavalla iskulla. Varjopisteet täyteen, kiekot tehostuvat 60 % neljäksi sekunniksi ja lähtöpaikkaan jää varjo — purskeen jälkeen on aina paluutie.", "cd": 0.0,
				"tip": "Teurastus vie selän taakse: laukaise se haavoittuneeseen ja jatka heti shurikenilla.", "scaling": "Skaalaa: hyökkäysvoima (kova), kohteen puuttuva elämä, ultin ranki"},
		},
	},
	"tide": {
		"name": "Tide",
		"role": "Fighter",
		"difficulty": 2,
		"hp": 240.0,
		"speed": 315.0,
		"ratings": {"kesto": 4, "liike": 4, "vahinko": 3, "tuki": 2},
		"weapon": "Vesikeihäs",
		"desc": "Virtaava taistelija. Kerää raivoa taistelusta ja purkaa sen vesikykyihin.",
		"color": Color("4ad4ff"),
		"color_b": Color("176d94"),
		"abilities": {
			"basic": {"name": "Keihäspisto", "desc": "Pitkä ja kapea pisto eteen.", "cd": 0.55,
				"tip": "Pisto on kapea mutta pitkä: pidä nokka kohteessa äläkä juokse kylkeen.", "scaling": "Skaalaa: hyökkäysvoima, iskunopeus"},
			"a1": {"name": "Vesivana", "desc": "Syöksy, joka jättää kiihdyttävän vanan. 3 latausta, lyhyt käyttöväli — lataukset palautuvat hitaasti. Ei kuluta raivoa.", "cd": 0.55,
				"tip": "Säästä yksi lataus paluumatkaan — kolme latausta ei tarkoita kolmea sisäänmenoa.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki; 3 latausta"},
			"a2": {"name": "Aalto", "desc": "Työntävä vesiaalto eteen, joka hidastaa. Kuluttaa raivoa.", "cd": 7.5,
				"tip": "Aalto työntää: käytä se erottamaan vihollinen tornistaan tai joukkueestaan.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki, raivo"},
			"dodge": {"name": "Virtaliuku", "desc": "Liukas väistö, joka antaa vauhtia.", "cd": 4.0,
				"tip": "Liuku antaa vauhtia — ketjuta se vanaan niin pääset kartan poikki.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki"},
			"ult": {"name": "Vesipatsas", "desc": "Pidä L2 ja valitse laskeutumisalue oikealla tatilla. Tide syöksyy sinne seinien läpi, nostaa viholliset ja iskee heidät alas.", "cd": 0.0,
				"tip": "Valitse laskeutuminen seinän yli: patsas nostaa ilmaan eikä kohde ehdi väistää.", "scaling": "Skaalaa: kykyvahinko (ap), ultin ranki"},
		},
	},
	"scout": {
		"name": "Scout",
		"role": "Ranger",
		"difficulty": 2,
		"hp": 180.0,
		"speed": 330.0,
		"ratings": {"kesto": 2, "liike": 3, "vahinko": 3, "tuki": 4},
		"weapon": "Vaahtopallokivääri",
		"desc": "Joukkueen silmät. Konekivääri isolla lippaalla (lataa kierähtämällä), ja osumat lataavat energiaa merkki- ja tainnutuspalloihin.",
		"color": Color("c9d16b"),
		"color_b": Color("6b7a2f"),
		"abilities": {
			"basic": {"name": "Konekivääri", "desc": "Pidä liipaisin pohjassa ryöpyttääksesi. Iso lipas, pitkä lataus — lataa kesken taistelun kierähtämällä (X).", "cd": 0.1,
				"tip": "Älä anna lippaan tyhjentyä taistelussa: kierähdä (X) kun jäljellä on kolmannes.", "scaling": "Skaalaa: hyökkäysvoima, kriittinen, iskunopeus"},
			"a1": {"name": "Merkkipanos", "desc": "Pitkän kantaman tarkkuuspanos: merkitty kohde ottaa +45 % vahinkoa kaikilta. Tähtää pitämällä nappia pohjassa.", "cd": 7.0,
				"tip": "Merkitse ennen joukkueen aloitusta: merkitty ottaa lisävahinkoa KAIKILTA, ei vain sinulta.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki"},
			"a2": {"name": "Tainnutuspallo", "desc": "Tähdättävä tahmea pallo, joka pamahtaa ja tainnuttaa pienellä alueella. Tähtää pitämällä nappia pohjassa.", "cd": 9.0,
				"tip": "Tähtää jalkoihin, ei kasvoihin: pallo pamahtaa alueeseen ja tainnuttaa vieressäkin.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki (tainnutus)"},
			"dodge": {"name": "Kierähdys", "desc": "Nopea rullaus, joka lataa lippaan heti täyteen.", "cd": 3.5,
				"tip": "Kierähdys on lataus: käytä se rytmissä äläkä odota automaattilatausta.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki"},
			"ult": {"name": "Merkkisade", "desc": "Merkitsee kaikki lähiviholliset ja kiihdyttää joukkueen.", "cd": 0.0,
				"tip": "Laukaise sade juuri ennen joukkueen sisäänmenoa: merkit ja vauhti kestävät koko aloituksen.", "scaling": "Skaalaa: ultin ranki (merkin voima ja kesto)"},
		},
	},
	"prism": {
		"name": "Prisma",
		"role": "Tuki",
		"difficulty": 3,
		"hp": 190.0,
		"speed": 315.0,
		"ratings": {"kesto": 2, "liike": 3, "vahinko": 3, "tuki": 5},
		"weapon": "Valoprisma",
		"desc": "Sädetuki. Kanavoi säteitä: toinen vahingoittaa ja hidastaa, toinen parantaa liittolaisia. Käyttää manaa.",
		"color": Color("5be0e0"),
		"color_b": Color("1f7d8c"),
		"abilities": {
			"basic": {"name": "Valonsäde", "desc": "Kevyt valoammus.", "cd": 0.5,
				"tip": "Perusammus on täytettä: säteet ovat Prisman oikea ase.", "scaling": "Skaalaa: hyökkäysvoima, iskunopeus"},
			"a1": {"name": "Polttosäde", "desc": "Pidä pohjassa: jatkuva säde joka hidastaa voimakkaasti ja tekee kohtalaista vahinkoa. Kuluttaa runsaasti manaa.", "cd": 0.0,
				"tip": "Pidä säde kiinni pakenevassa: hidastus on kovempi kuin vahinko.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki, mana"},
			"a2": {"name": "Hoitosäde", "desc": "Pidä pohjassa: jatkuva säde joka parantaa liittolaisia. Kuluttaa manaa.", "cd": 0.0,
				"tip": "Säde ei paranna sinua — pysy liittolaisen kantamalla ja katkaise vasta kun palkki on täynnä.", "scaling": "Skaalaa: kyvyn ranki ja hoivasydän, mana"},
			"dodge": {"name": "Valonpyrähdys", "desc": "Nopea väistöliuku.", "cd": 3.5,
				"tip": "Katkaise säde vasta pyrähdyksen jälkeen: pelkkä liike ei keskeytä kanavointia.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki"},
			"ult": {"name": "Loistokehä", "desc": "Pidä pohjassa nähdäksesi alue, vapauta: sisällä olevat liittolaiset saavat lisää vahinkoa ja vauhtia.", "cd": 0.0,
				"tip": "Aseta kehä sinne missä joukkue TAISTELEE: sisällä olevat lyövät kovempaa.", "scaling": "Skaalaa: ultin ranki (vahinkobuffi ja kesto)"},
		},
	},
	"rift": {
		"name": "Rift",
		"role": "Assassin",
		"difficulty": 3,
		"hp": 120.0,
		"speed": 355.0,
		"ratings": {"kesto": 1, "liike": 5, "vahinko": 5, "tuki": 1},
		"weapon": "Tyhjyyden tikari",
		"desc": "Tyhjyyskahakoitsija. Lataa ja purkaa: perusiskut kasaavat pinoja, merkki varppaa selän taakse ja räjäytys teloittaa. Ultti pysäyttää ajan ympäriltä.",
		"color": Color("9d4edd"),
		"color_b": Color("3a0e5c"),
		"abilities": {
			"basic": {"name": "Tyhjyysviilto", "desc": "Melee-viilto joka lataa pinon kohteeseen (enintään 5) JA tekee sitä kovempaa mitä enemmän pinoja kohteessa jo on. Ajanpysäytyksen aikana viilto lataa kaksi pinoa kerralla.", "cd": 0.32,
				"tip": "Pidä kohde lähellä: jokainen viilto lataa pinon ja tekee kovempaa kun pinoja on jo.", "scaling": "Skaalaa: hyökkäysvoima, kriittinen, kohteen pinot"},
			"a1": {"name": "Tyhjyysmerkki", "desc": "Pidä R1 ja vapauta heittääksesi merkin. Vihollisosuma tekee vahinkoa, lataa kaksi pinoa ja merkitsee kohteen. Toinen painallus varppaa merkille: viholliseen selän taakse iskien, omaan sankariin pakoreittinä. Varppaus avaa 0,45 sekunnin tyhjyysaukon.", "cd": 9.0,
				"tip": "Heitä merkki, varppaa selän taakse ja räjäytä heti — tyhjyysaukko kestää 0,45 s.", "scaling": "Skaalaa: hyökkäysvoima (kova), kykyvahinko, kyvyn ranki"},
			"a2": {"name": "Räjäytys", "desc": "Melee-isku joka räjäyttää kohteen pinot: enemmän pinoja = enemmän vahinkoa, ja neljästä pinosta alkaen mukaan tulee teloitusosuus puuttuvasta elämästä. Tyhjyysaukon sisällä 30 % kovempaa. Kulutetut pinot hyvittävät väistön jäähdytystä; täydet 5 nollaa sekä räjäytyksen että väistön.", "cd": 7.0,
				"tip": "Odota vähintään neljä pinoa: siitä alkaen räjäytys teloittaa puuttuvan elämän mukaan.", "scaling": "Skaalaa: hyökkäysvoima (kova), pinojen määrä, kohteen puuttuva elämä"},
			"dodge": {"name": "Tyhjyysloikka", "desc": "Nopea tyhjyysloikka. Räjäytys hyvittää sen jäähdytystä, joten purske ostaa poistumisen.", "cd": 3.5,
				"tip": "Räjäytys hyvittää loikan jäähdytystä — purske ensin, poistuminen heti perään.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki, kulutetut pinot"},
			"ult": {"name": "Ajanpysäytys", "desc": "Pysäyttää ajan ympärillä: kaikki muut (myös omat) jäätyvät kahdeksi sekunniksi, sinä liikut vapaasti. Sisään jääneet viholliset ottavat vahinkoa ja saavat kaksi pinoa, ja pysäytyksen ajan vahinkosi on 40 % suurempi.", "cd": 0.0,
				"tip": "Pysäytä aika kun pinot ovat jo kohteessa: pysäytyksen aikana vahinkosi on 40 % suurempi.", "scaling": "Skaalaa: hyökkäysvoima (kova), kykyvahinko, ultin ranki"},
		},
	},
	"titan": {
		"name": "Titaani",
		"role": "Tankki",
		"difficulty": 2,
		"hp": 380.0,
		"speed": 300.0,
		"ratings": {"kesto": 5, "liike": 2, "vahinko": 2, "tuki": 3},
		"weapon": "Rautakourat",
		"desc": "Murskaava jättiläinen. Tekee vähän vahinkoa mutta kestää valtavasti: nappaa vihollisen kiinni ja heittää pois, ja kuluttaa raivoa suojautuakseen ja parantuakseen.",
		"color": Color("c05a3a"),
		"color_b": Color("4a1b12"),
		"abilities": {
			"basic": {"name": "Murskaava isku", "desc": "Raskas lähi-isku. Jokainen osuma lyhentää Tartu ja heitä -kyvyn jäähdytystä.", "cd": 0.6,
				"tip": "Jokainen osuma lyhentää tartunnan jäähdytystä: lyö minioneita kun tartunta on jäissä.", "scaling": "Skaalaa: hyökkäysvoima, iskunopeus"},
			"a1": {"name": "Tartu ja heitä", "desc": "Nappaa edessä olevan vihollisen ja heittää sen tähtäyssuuntaan, jättäen lyhyen tainnutuksen. Raivotilan aikana nostaa kaikki lähiviholliset ilmaan.", "cd": 7.0,
				"tip": "Heitä kohde OMAAN joukkueeseesi päin, älä pois — heitto on lahja liittolaisille.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki (tainnutus)"},
			"a2": {"name": "Raivosuoja", "desc": "Pidä pohjassa: kuluttaa raivoa, vähentää otettua vahinkoa joka suunnasta ja palauttaa elämää.", "cd": 6.0,
				"tip": "Purista suojaa vasta kun osumia tulee: raivo palaa nopeasti mutta ei tyhjästä.", "scaling": "Skaalaa: kyvyn ranki (vaimennus ja parannus), raivo"},
			"dodge": {"name": "Syöksyrynnäkkö", "desc": "Raskas syöksy, joka tönäisee ja hidastaa osuessaan.", "cd": 4.5,
				"tip": "Rynnäkkö hidastaa osuessaan: käytä se kiinniottoon, ei pakoon.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki"},
			"ult": {"name": "Raivotila", "desc": "Muuttuu hetkeksi berserkiksi: nopeampi liike, iskunopeus ja vahinko nousevat, ja Tartu ja heitä muuttuu alueen ilmaanheitoksi.", "cd": 0.0,
				"tip": "Raivotilassa tartunta nostaa KAIKKI lähellä olevat — laukaise se rykelmään.", "scaling": "Skaalaa: kykyvahinko (ap), ultin ranki"},
		},
	},
	"hush": {
		"name": "Hush",
		"role": "Tuki",
		"difficulty": 3,
		"hp": 205.0,
		"speed": 320.0,
		"ratings": {"kesto": 3, "liike": 3, "vahinko": 2, "tuki": 5},
		"weapon": "Vaimennuskello",
		"desc": "Kontrollituki. Suojaa liittolaisia isoilla kilvillä (paljon enemmän kuin parantaa) ja tukahduttaa vihollisten liikkeen ja kyvyt. Käyttää manaa.",
		"color": Color("a678f0"),
		"color_b": Color("4a2d78"),
		"abilities": {
			"basic": {"name": "Kaikuisku", "desc": "Läpäisevä ääniammus, joka nakuttaa vihollisia.", "cd": 0.5,
				"tip": "Läpäisevä ammus: linjaa se minionirivin suuntaisesti.", "scaling": "Skaalaa: hyökkäysvoima, iskunopeus"},
			"a1": {"name": "Suojasointu", "desc": "Iso suojakilpi eniten kärsineelle liittolaiselle ja pieni paikkaus päälle. Kilpiää paljon enemmän kuin parantaa.", "cd": 7.0,
				"tip": "Kilpi kestää vain hetken: anna se juuri ennen osumaa, älä varmuuden vuoksi.", "scaling": "Skaalaa: kyvyn ranki ja hoivasydän"},
			"a2": {"name": "Dissonanssikenttä", "desc": "Heittää alueen, joka hidastaa voimakkaasti ja kalvaa vihollisia. Pidä L1 pohjassa ja siirrä maalia oikealla tatilla.", "cd": 8.0,
				"tip": "Kenttä hidastaa rajusti: heitä se pakoreitille, niin kohde ei pääse ulos.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki"},
			"dodge": {"name": "Haamukello", "desc": "Hetkellinen immuniteetti ja nopea haamuliuku seinien läpi, jättää pienen suojakilven. Pitkä jäähdytys.", "cd": 7.0,
				"tip": "Pitkä jäähdytys: käytä haamuliuku seinän läpi vasta kun se pelastaa hengen.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki (kilpi)"},
			"ult": {"name": "Suuri Vaimennus", "desc": "Pidä L2 ja siirrä suurta vaimennusaluetta oikealla tatilla. Lyhyen varoituksen jälkeen viholliset juurtuvat ja menettävät kykynsä.", "cd": 0.0,
				"tip": "Vaimennus vie kyvyt: aseta se vihollisen aloittajan päälle, ei takalinjaan.", "scaling": "Skaalaa: ultin ranki (juurrutuksen ja vaimennuksen kesto)"},
		},
	},
	"obsidian": {
		"name": "Obsidian",
		"role": "Tankki",
		"difficulty": 2,
		"hp": 370.0,
		"speed": 290.0,
		"ratings": {"kesto": 5, "liike": 2, "vahinko": 2, "tuki": 3},
		"weapon": "Obsidiaaninyrkit",
		"desc": "Kivinen jättiläinen. Hallitsee lähialuetta, kääntää vahingon takaisin hyökkääjiin ja lataa itsensä eläväksi pommiksi. Kerää raivoa taistelusta.",
		"color": Color("8a4a52"),
		"color_b": Color("2e181c"),
		"abilities": {
			"basic": {"name": "Kiviisku", "desc": "Raskas isku joka hidastaa viholliset ja parantaa itseä osuessaan.", "cd": 0.6,
				"tip": "Isku hidastaa ja parantaa: pysy kiinni yhdessä kohteessa äläkä vaihtele.", "scaling": "Skaalaa: hyökkäysvoima, iskunopeus, elinvoiman imu"},
			"a1": {"name": "Louhintaloikka", "desc": "Hyppää tähtäyssuuntaan seinien yli ja iskee alas tainnuttavalla aluevahingolla. Tähtää pitämällä nappia pohjassa.", "cd": 8.0,
				"tip": "Loikka menee seinien yli: tule sisään sieltä mistä sinua ei odoteta.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki (tainnutus)"},
			"a2": {"name": "Kiviho", "desc": "Pidä pohjassa: torjuu otettua vahinkoa joka suunnasta ja heijastaa osan takaisin hyökkääjään. Kuluttaa raivoa.", "cd": 6.0,
				"tip": "Kiviho kannattaa juuri ennen vihollisen purskeikkunaa: se heijastaa osan takaisin.", "scaling": "Skaalaa: kyvyn ranki (torjunta ja heijastus), raivo"},
			"dodge": {"name": "Kivirynnäkkö", "desc": "Raskas syöksy, joka tönäisee ja hidastaa osuessaan.", "cd": 5.0,
				"tip": "Rynnäkkö hidastaa: se on kiinniottoväline eikä pakoliike.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki"},
			"ult": {"name": "Ydinräjähdys", "desc": "Lataa näkyvästi 2,5 sekuntia ottaen 80 % vähemmän vahinkoa. Sitten räjähtää: lähempänä olevat viholliset ottavat enemmän vahinkoa.", "cd": 0.0,
				"tip": "Lataus näkyy 2,5 s — pysy kiinni vihollisessa, lähempänä oleva ottaa enemmän.", "scaling": "Skaalaa: kykyvahinko (ap), ultin ranki, etäisyys keskustaan"},
		},
	},
	"lance": {
		"name": "Lance",
		"role": "Fighter",
		"difficulty": 3,
		"hp": 240.0,
		"speed": 320.0,
		"ratings": {"kesto": 3, "liike": 4, "vahinko": 4, "tuki": 1},
		"weapon": "Teräskeihäs",
		"desc": "Kaksintaistelija. Kasaa merkkejä kohteisiin ja viimeistelee ne isolla iskulla. Kerää raivoa taistelusta.",
		"color": Color("cf4459"),
		"color_b": Color("48141f"),
		"abilities": {
			"basic": {"name": "Keihäänpisto", "desc": "Kapea pisto eteen. Joka 3. osuma merkitsee kohteen; 3 merkkiä laukaisee viimeistelyn (bonusvahinko + elinvoiman imu + vauhti).", "cd": 0.5,
				"tip": "Joka kolmas osuma merkitsee ja kolmas merkki laukaisee viimeistelyn: älä vaihda kohdetta.", "scaling": "Skaalaa: hyökkäysvoima, kriittinen, iskunopeus"},
			"a1": {"name": "Lävistyssyöksy", "desc": "Syöksy seinien ja sankarien läpi, joka merkitsee jokaisen läpi mennyn vihollisen. Syöksyn aikana immuuni tainnutuksille. Tähtää pitämällä nappia pohjassa.", "cd": 8.0,
				"tip": "Syöksy sankarin LÄPI: se merkitsee jokaisen matkalla olevan ja on tainnutusimmuuni.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki"},
			"a2": {"name": "Pyörremyrsky", "desc": "Pyörivä keihäs vahingoittaa ja vaimentaa lähiviholliset sekä merkitsee heidät. Kuluttaa raivoa.", "cd": 8.0,
				"tip": "Pyörre vaimentaa: käytä se kun vihollinen aikoo castata, ei täytteenä.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki, raivo"},
			"dodge": {"name": "Sivuloikka", "desc": "Nopea väistöloikka.", "cd": 4.0,
				"tip": "Sivuloikka pitää sinut merkityn kohteen kantamalla — älä loiko pois.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki"},
			"ult": {"name": "Taivaankeihäs", "desc": "Pidä L2 ja valitse laskeutumispiste oikealla tatilla. Lance iskee alueelle ja saa hetkeksi nopeammat perusiskut.", "cd": 0.0,
				"tip": "Laskeudu kohteen taakse: ultin jälkeen perusiskut ovat nopeammat ja merkit kertyvät.", "scaling": "Skaalaa: kykyvahinko (ap), ultin ranki"},
		},
	},
	"salvo": {
		"name": "Salvo",
		"role": "Ranger",
		"difficulty": 3,
		"hp": 175.0,
		"speed": 330.0,
		"ratings": {"kesto": 2, "liike": 3, "vahinko": 5, "tuki": 2},
		"weapon": "Kranaatinheitin ja morttari",
		"desc": "Raskas tuhotyöläinen. Kylvää miinoja, ennakoi pitkän kantaman morttarilla ja lukittuu ultissa näkyväksi bunkkeriksi ohjaamaan kiihtyvää ohjusta.",
		"color": Color("e8722e"),
		"color_b": Color("5c2a10"),
		"abilities": {
			"basic": {"name": "Sirpalekranaatti", "desc": "Nopea pyörivä kranaattiammus.", "cd": 0.45,
				"tip": "Kranaatti lentää hitaasti: ennakoi liikettä puoli hahmonmittaa.", "scaling": "Skaalaa: hyökkäysvoima, kriittinen, iskunopeus"},
			"a1": {"name": "Miina", "desc": "Heittää miinan, joka laukeaa vihollisen lähestyessä. Enintään 5 kentällä; kun raja täyttyy, vanhin räjähtää tehden tilaa.", "cd": 1.3,
				"tip": "Kylvä miinat kulkureitille etukäteen: taistelun aikana asetettu miina ei ehdi laueta.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki; 5 kentällä"},
			"a2": {"name": "Kaarimorttari", "desc": "Pitkän kantaman voimakas kranaatti putoaa hitaasti merkittyyn pisteeseen. Pidä L1 pohjassa, siirrä maalia oikealla tatilla ja vapauta — vaikea osua, mutta kova vahinko.", "cd": 5.0,
				"tip": "Pitkä lentoaika palkitsee ennakoinnin: tähtää sinne mihin kohde pakenee.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki"},
			"dodge": {"name": "Leijunta", "desc": "Nousee ilmaan kohdistamattomaksi (immuuni) hetkeksi ja liikkuu kelluen — voi käyttää kykyjä ilmassa. Pitkä jäähdytys.", "cd": 8.0,
				"tip": "Leijunnassa olet immuuni ja voit yhä castata — nouse ilmaan juuri ennen osumaa.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki"},
			"ult": {"name": "Bunkkeriohjus", "desc": "Lukittuu näkyväksi bunkkeriksi ja ottaa 72 % vähemmän vahinkoa. Laukaisee valtavan ohjuksen, joka kiihtyy koko lennon ajan ja muuttuu vaikeaksi kääntää. Vahinko kasvaa lennon kiihtyessä: lähilaukaus on heikko, pitkä lento tuhoisa (tehomittari ohjuksen ympärillä). Ohjaa vasemmalla tai oikealla tatilla.", "cd": 0.0,
				"tip": "Anna ohjuksen kiihtyä: lähilaukaus on heikko, pitkä lento tuhoisa — mutta kääntäminen vaikeutuu.", "scaling": "Skaalaa: kykyvahinko (ap), ultin ranki, ohjuksen lentonopeus"},
		},
	},
	"kaira": {
		"name": "Kaira",
		"role": ROLE_JUNGLER,
		"archetype": "Bruiser",
		"difficulty": 2,
		"hp": 285.0,
		"speed": 318.0,
		"ratings": {"kesto": 4, "liike": 3, "vahinko": 4, "tuki": 1},
		"weapon": "Sulapora",
		"desc": "Sulakuoriainen. Kaivertaa maan auki hehkuvalla poralla ja imee kuumuudesta voimansa: jokainen lähiosuma parantaa, jokainen kyky jättää maahan laavaa.",
		"color": Color("ff5f1f"),
		"color_b": Color("4d1204"),
		"abilities": {
			"basic": {"name": "Poranterä", "desc": "Leveä poraisu eteen. Kaira parantuu reilulla neljänneksellä tekemästään vahingosta — mitä useampaan osuu, sitä kauemmin pysyy pystyssä.", "cd": 0.52,
				"tip": "Osu useaan kerralla: Kaira parantuu reilulla neljänneksellä tekemästään vahingosta.", "scaling": "Skaalaa: hyökkäysvoima, iskunopeus, elinvoiman imu"},
			"a1": {"name": "Sulasyöksy", "desc": "Pidä R1 ja suuntaa: Kaira ryntää pora edellä. Reitillä olevat lentävät sivuun ja maahan jää palava laavavana, jossa Kaira itse parantuu.", "cd": 7.5,
				"tip": "Ryntää kohteen LÄPI: laavavana jää perään ja sinä paranut siinä seisoessasi.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki"},
			"a2": {"name": "Maanjyrä", "desc": "Kuluttaa raivon yhteen maaniskuun. Sulapiikit purkautuvat renkaana: vahinko, sinko ulos ja hidastus — ja Kaira parantuu jokaisesta osumasta.", "cd": 7.5,
				"tip": "Purista raivo vasta kun useampi on renkaan sisällä: jokainen osuma parantaa.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki, raivo"},
			"dodge": {"name": "Kaivautuminen", "desc": "Kaira sukeltaa maan alle (osumaton) ja puhkaisee pinnan uudessa paikassa sulapurkauksena. Väistö on aina myös hyökkäys.", "cd": 7.0,
				"tip": "Kaivautuminen on hyökkäys: puhkaise pinta vihollisen alta, älä pakomatkan päässä.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki"},
			"ult": {"name": "Sulakita", "desc": "Pidä L2 ja suuntaa: Kaira repii maahan pitkän tulikuilun. Viiva telegrafoidaan ennen purkausta; osuma sinkoaa kaiken sivuun ja jättää laavaa koko matkalle.", "cd": 0.0,
				"tip": "Viiva telegrafoidaan: vedä se pakoreitin poikki, älä kohteen nykyiseen paikkaan.", "scaling": "Skaalaa: kykyvahinko (ap), ultin ranki"},
		},
	},
	"vesper": {
		"name": "Vesper",
		"role": ROLE_JUNGLER,
		"archetype": "Ranger",
		"difficulty": 3,
		"hp": 190.0,
		"speed": 336.0,
		"ratings": {"kesto": 2, "liike": 4, "vahinko": 5, "tuki": 1},
		"weapon": "Fosforisirppi",
		"desc": "Fosforijahtaaja. Merkitsee saaliin ja lopettaa sen: teloituskyvyt tekevät sitä enemmän vahinkoa mitä vähemmän kohteella on elämää jäljellä.",
		"color": Color("a6f23e"),
		"color_b": Color("234f17"),
		"abilities": {
			"basic": {"name": "Fosforipultti", "desc": "Nopea pultti. Merkittyyn kohteeseen se tekee lisävahinkoa ja palauttaa energiaa — merkki kannattaa aina käyttää.", "cd": 0.46,
				"tip": "Merkittyyn kohteeseen jokainen pultti tekee lisää ja palauttaa energiaa — käytä merkki loppuun.", "scaling": "Skaalaa: hyökkäysvoima, kriittinen, iskunopeus"},
			"a1": {"name": "Fosforipiikki", "desc": "Pidä R1 tähdätäksesi pitkän läpäisevän piikin. MERKITSEE saaliin kuudeksi sekunniksi: merkitty ottaa lisävahinkoa ja avaa Teloituksen.", "cd": 7.5,
				"tip": "Merkitse ENSIN: merkki avaa Teloituksen ja nostaa kaiken kohteeseen tulevan vahingon.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki"},
			"a2": {"name": "Teloitus", "desc": "Pidä L1 ja tähtää raskas pultti. Vahinko kasvaa sen mukaan kuinka paljon kohteelta PUUTTUU elämää; merkittyyn 25 % kovempaa. Tappo hyvittää 5 s jäähdytyksestä.", "cd": 8.0,
				"tip": "Älä ammu täyteen elämään: Teloitus kasvaa puuttuvan elämän mukaan ja tappo hyvittää 5 s.", "scaling": "Skaalaa: kykyvahinko (ap), kohteen puuttuva elämä, merkki"},
			"dodge": {"name": "Fosforiloikka", "desc": "Pitkä loikka osumattomana ja lyhyt vauhtibuffi. Jahtaajan oma etäisyydenhallinta.", "cd": 6.0,
				"tip": "Loikka on etäisyydenhallintaa: pidä väli koko ajan, älä vasta viime hetkellä.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki"},
			"ult": {"name": "Fosforisalama", "desc": "Pidä L2 ja suuntaa: ohut kiskolaukaus lävistää kaiken linjalla 1050 px matkalta. Vahinko kasvaa jokaisen kohteen puuttuvan elämän mukaan — koko joukkueen lopetusnappi.", "cd": 0.0,
				"tip": "Odota että linjalla on kaksi haavoittunutta: vahinko lasketaan jokaisen puuttuvasta elämästä.", "scaling": "Skaalaa: kykyvahinko (ap), kohteiden puuttuva elämä, ultin ranki"},
		},
	},
	"myria": {
		"name": "Myria",
		"role": ROLE_JUNGLER,
		"archetype": "Mage",
		"difficulty": 3,
		"hp": 205.0,
		"speed": 326.0,
		"ratings": {"kesto": 3, "liike": 3, "vahinko": 4, "tuki": 4},
		"weapon": "Kukkasauva",
		"desc": "Orkideahenki. Istuttaa taistelukentälle orkideoita ja puhkaisee ne kukkimaan. Yksi selkeä silmukka: ISTUTA — KUKI.",
		"color": Color("c77bff"),
		"color_b": Color("471668"),
		"abilities": {
			"basic": {"name": "Siitepölysyöksy", "desc": "Kevyesti hakeutuva itiöpallo, joka hidastaa hetkeksi. Kun kukkia on maassa, osuma parantaa Myriaa.", "cd": 0.56,
				"tip": "Kun kukkia on maassa, perusosuma parantaa sinua — istuta ennen kahakkaa.", "scaling": "Skaalaa: hyökkäysvoima, iskunopeus"},
			"a1": {"name": "Kukkaistutus", "desc": "Pidä R1 ja sijoita orkidea. Se polttaa vihollisia ja parantaa liittolaisia 11 sekunnin ajan. Enintään kolme kerrallaan; neljäs kuihduttaa vanhimman.", "cd": 6.0,
				"tip": "Istuta kukat sinne missä taistelu KÄYDÄÄN: ne polttavat vihollisia ja parantavat omia 11 s.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki; enintään 3"},
			"a2": {"name": "Kukinta", "desc": "Kaikki istutetut orkideat puhkeavat kerralla omalla paikallaan: 46 vahinkoa ja hidastus, ja Myria parantuu jokaisesta puhjenneesta kukasta. Ilman kukkia Myria kukkii itse.", "cd": 8.0,
				"tip": "Puhkaise vasta kun maassa on vähintään kaksi kukkaa — yksi kukka on hukkaan heitetty kukinta.", "scaling": "Skaalaa: kykyvahinko (ap), kukkien määrä, kyvyn ranki"},
			"dodge": {"name": "Terälehtiliuku", "desc": "Myria hajoaa terälehdiksi ja liukuu sivuun osumattomana. Puhdistava liike: henki livahtaa kontrollista.", "cd": 5.0,
				"tip": "Liuku on puhdistava: käytä se kontrollista irti, ei pelkkään matkantekoon.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki"},
			"ult": {"name": "Orkideapuutarha", "desc": "Pidä L2 ja avaa kokonainen puutarha. Iso kenttä polttaa vihollisia ja parantaa liittolaisia, ja kehälle nousee viisi orkideaa — puutarha on myös ladattu Kukinta.", "cd": 0.0,
				"tip": "Puutarha on myös ladattu Kukinta: avaa se objektiivin päälle ja purista kukinta perään.", "scaling": "Skaalaa: kykyvahinko (ap), ultin ranki"},
		},
	},
	"torq": {
		"name": "Torq",
		"role": ROLE_JUNGLER,
		"archetype": "Tankki",
		"difficulty": 2,
		"hp": 365.0,
		"speed": 302.0,
		"ratings": {"kesto": 5, "liike": 2, "vahinko": 2, "tuki": 4},
		"weapon": "Magneettivasara",
		"desc": "Magneettivartija. Jokainen kyky liikuttaa vihollista: perusisku nykäisee, koukku raahaa, Napalukko imee koko rykelmän. Vahinko on pieni — arvo on siinä, missä vihollinen seisoo.",
		"color": Color("7b8cff"),
		"color_b": Color("1b2456"),
		"abilities": {
			"basic": {"name": "Magneettivasara", "desc": "Leveä vasaranisku, joka nykäisee osuneen kohteen askeleen lähemmäs. Torqin luota on aina vaikea päästä pois.", "cd": 0.64,
				"tip": "Jokainen osuma nykäisee kohdetta lähemmäs: naputtelu on kiinnipitoa.", "scaling": "Skaalaa: hyökkäysvoima, iskunopeus"},
			"a1": {"name": "Magneettikoukku", "desc": "Pidä R1 ja tähtää: magneettiankkuri raahaa ensimmäisen osuman Torqin eteen. Monsterit tulevat kovempaa ja tainnuttuvat hetkeksi.", "cd": 7.5,
				"tip": "Koukku raahaa ensimmäisen osuman eteesi — tähtää minionirivin ohi, ei sen läpi.", "scaling": "Skaalaa: kykyvahinko (ap), kyvyn ranki"},
			"a2": {"name": "Napalukko", "desc": "Torq kääntää navat päälle: kaikki ympärillä imaistaan kiinni ja JUURRUTETAAN paikoilleen. Torq saa kilven osumien määrän mukaan. Tämä on aloitus.", "cd": 7.0,
				"tip": "Napalukko on aloitus: juurruta rykelmä ja anna joukkueen tulla perässä.", "scaling": "Skaalaa: kyvyn ranki (juurrutus ja kilpi), raivo"},
			"dodge": {"name": "Magneettiliuku", "desc": "Torq irrottaa navat maasta ja liukuu magneettisesti sivuun: lyhyt osumattomuus ja kilpi. Tankin oikea pakoliike.", "cd": 8.0,
				"tip": "Tankin oikea pakoliike: liu'u ulos vasta kun kohde on jo juurrutettu.", "scaling": "Skaalaa: jäähdytyksen alennus, väistön ranki (kilpi)"},
			"ult": {"name": "Napakenttä", "desc": "Pidä L2 ja sijoita valtava magneettikaivo. Sisällä olevia vedetään jatkuvasti keskustaan, ne hidastuvat rajusti ja juurtuvat pulssein — kukaan ei kävele ulos.", "cd": 0.0,
				"tip": "Kaivo vetää jatkuvasti keskustaan: aseta se kapeikkoon niin kukaan ei kävele ulos.", "scaling": "Skaalaa: ultin ranki (veto, hidastus ja juurrutus)"},
		},
	},
}


# Neutraali oletusmääritys tuntemattomille tunnuksille (esim. viidakko-olennot,
# joita ei ole sankarilistassa). Näin get_def ei kaadu vaikka sitä kutsuttaisiin
# ei-sankarilla (bottien roolihaku alive_enemies-listasta osuu myös olentoihin).
const DEFAULT_DEF := {
	"name": "?",
	"role": "Tankki",          # neutraali -> ei kohtele "takalinjana"
	"difficulty": 1,
	"hp": 200.0,
	"speed": 300.0,
	"ratings": {"kesto": 3, "liike": 3, "vahinko": 3, "tuki": 3},
	"weapon": "",
	"desc": "",
	"color": Color("8f9aa8"),
	"color_b": Color("4a505c"),
	"abilities": {},
}


static func get_def(id: String) -> Dictionary:
	return HEROES.get(id, DEFAULT_DEF)


static func ability(id: String, slot: String) -> Dictionary:
	return HEROES[id]["abilities"][slot]


static func cooldown(id: String, slot: String) -> float:
	return HEROES[id]["abilities"][slot]["cd"]
