class_name HeroDef
## Sankarien staattiset määrittelyt: nimet, roolit, tilastot, kyvyt ja värit.
## Sankariluokat lukevat cooldownit ja perustilastot täältä, jotta
## käyttöliittymä ja pelilogiikka pysyvät aina samassa linjassa.

const ORDER := [
	"bastion", "ember", "luma", "blink", "bramble", "quill",
	"boulder", "volt", "maestro", "shade", "tide", "scout",
	"prism", "rift", "titan",
]

const HEROES := {
	"bastion": {
		"name": "Bastion",
		"role": "Tankki",
		"difficulty": 1,
		"hp": 340.0,
		"speed": 295.0,
		"ratings": {"kesto": 5, "liike": 2, "vahinko": 1, "tuki": 4},
		"weapon": "Kilpi ja nuija",
		"desc": "Rintaman kallio. Suojaa joukkuetta edestä ja pitää linjan.",
		"color": Color("86ccd9"),
		"color_b": Color("2e5f74"),
		"abilities": {
			"basic": {"name": "Nuijan heilautus", "desc": "Leveä pyyhkäisy eteen.", "cd": 0.6},
			"a1": {"name": "Kilpivalli", "desc": "Pidä pohjassa nostaaksesi ison etukilven: vaimentaa Bastionin ottamaa vahinkoa ja torjuu edestä tulevat vihollisammukset — suojaa myös takana olevat liittolaiset. Kuluttaa energiaa.", "cd": 9.0},
			"a2": {"name": "Vetoisku", "desc": "Vetää ympäröivät viholliset eteen ja tainnuttaa (ei vahinkoa) — kerää viholliset haltuun kilven eteen.", "cd": 7.5},
			"dodge": {"name": "Rynnäkkö", "desc": "Raskas syöksy, joka tönäisee vihollisia.", "cd": 5.0},
			"ult": {"name": "Linnake", "desc": "Suuri kupoli, joka torjuu vihollisammukset ja kilpiää liittolaiset.", "cd": 0.0},
		},
	},
	"ember": {
		"name": "Ember",
		"role": "Mage",
		"difficulty": 2,
		"hp": 170.0,
		"speed": 320.0,
		"ratings": {"kesto": 2, "liike": 3, "vahinko": 5, "tuki": 1},
		"weapon": "Tulilyhty",
		"desc": "Alueiden hallitsija. Käyttää manaa — voi spämmätä loitsuja kunnes mana loppuu, sitten se palautuu.",
		"color": Color("ff8a4a"),
		"color_b": Color("b33b17"),
		"abilities": {
			"basic": {"name": "Tulipallo", "desc": "Suora ammus, joka sytyttää jälkipolton.", "cd": 0.55},
			"a1": {"name": "Liekkilammikko", "desc": "Heittää palavan alueen, joka polttaa vihollisia. Tähtää pitämällä nappia pohjassa.", "cd": 8.0},
			"a2": {"name": "Lämpöaalto", "desc": "Viuhkapurkaus eteen: vahinko, työntö ja jälkipoltto.", "cd": 7.0},
			"dodge": {"name": "Kipinäliuku", "desc": "Nopea liuku, joka jättää kipinäjäljen.", "cd": 4.0},
			"ult": {"name": "Tulimyrsky", "desc": "Laajeneva liekkirengas, joka jättää lammikoita.", "cd": 0.0},
		},
	},
	"luma": {
		"name": "Luma",
		"role": "Tuki",
		"difficulty": 2,
		"hp": 200.0,
		"speed": 325.0,
		"ratings": {"kesto": 3, "liike": 3, "vahinko": 2, "tuki": 5},
		"weapon": "Valosauva",
		"desc": "Joukkueen sydän. Käyttää manaa — voi ketjuttaa hoitoja ja kilpiä kunnes mana loppuu, sitten se palautuu.",
		"color": Color("ffe9a8"),
		"color_b": Color("d9a13f"),
		"abilities": {
			"basic": {"name": "Valopulssi", "desc": "Ammus, joka vahingoittaa vihollisia ja parantaa liittolaiset läpi mennessään.", "cd": 0.5},
			"a1": {"name": "Hoitokehä", "desc": "Parantava purkaus Luman ympärillä.", "cd": 8.0},
			"a2": {"name": "Suojasäde", "desc": "Suojakilpi eniten kärsineelle liittolaiselle.", "cd": 7.0},
			"dodge": {"name": "Pyrähdys", "desc": "Kevyt ja nopea väistö, joka antaa vauhtia.", "cd": 3.5},
			"ult": {"name": "Valokenttä", "desc": "Suuri alue, joka parantaa ja nopeuttaa liittolaisia.", "cd": 0.0},
		},
	},
	"blink": {
		"name": "Blink",
		"role": "Assassin",
		"difficulty": 3,
		"hp": 148.0,
		"speed": 360.0,
		"ratings": {"kesto": 1, "liike": 5, "vahinko": 5, "tuki": 1},
		"weapon": "Kaksi valomiekkaa",
		"desc": "Välähdys pimeässä. Energia ruokkii teleportteja — hyökkääminen antaa lisää liikkuvuutta.",
		"color": Color("b48aff"),
		"color_b": Color("5b2f9e"),
		"abilities": {
			"basic": {"name": "Valoviilto", "desc": "Nopea kaksoisviilto. Selkäänisku tekee 50 % lisää.", "cd": 0.4},
			"a1": {"name": "Teleportti", "desc": "Siirtyy hetkessä tähtäyksen suuntaan.", "cd": 6.0},
			"a2": {"name": "Valoviuhka", "desc": "Heittää kolme valoterää viuhkana.", "cd": 7.0},
			"dodge": {"name": "Sivuaskel", "desc": "Salamannopea väistöliike.", "cd": 3.0},
			"ult": {"name": "Varjotanssi", "desc": "Iskee sarjan teleportteja lähivihollisten läpi.", "cd": 0.0},
		},
	},
	"bramble": {
		"name": "Bramble",
		"role": "Fighter",
		"difficulty": 2,
		"hp": 250.0,
		"speed": 310.0,
		"ratings": {"kesto": 4, "liike": 3, "vahinko": 3, "tuki": 2},
		"weapon": "Köynnösruoska",
		"desc": "Piikikäs lähitaistelija. Kerää raivoa taistelusta ja purkaa sen kykyihin.",
		"color": Color("7ed957"),
		"color_b": Color("2f7a33"),
		"abilities": {
			"basic": {"name": "Ruoskanisku", "desc": "Kaareva pyyhkäisy, joka imee elinvoimaa osumista.", "cd": 0.55},
			"a1": {"name": "Juurisidonta", "desc": "Köynnös, joka juurruttaa ensimmäisen osuman paikoilleen. Tähtää pitämällä nappia pohjassa.", "cd": 8.0},
			"a2": {"name": "Piikkipyörre", "desc": "Piikit sinkoutuvat ympärille ja jättävät hidastavan piikkialueen.", "cd": 7.5},
			"dodge": {"name": "Köynnösheitto", "desc": "Vetäisee itsensä ruoskalla eteenpäin.", "cd": 4.0},
			"ult": {"name": "Piikkipuutarha", "desc": "Suuri alue, joka juurruttaa, hidastaa ja pistelee vihollisia.", "cd": 0.0},
		},
	},
	"quill": {
		"name": "Quill",
		"role": "Ranger",
		"difficulty": 2,
		"hp": 175.0,
		"speed": 330.0,
		"ratings": {"kesto": 2, "liike": 3, "vahinko": 4, "tuki": 2},
		"weapon": "Jousi",
		"desc": "Tarkka-ampuja. Osumat lataavat energiaa, joka ruokkii erikoislaukauksia — tarkkuus palkitaan.",
		"color": Color("5fd0a0"),
		"color_b": Color("1f6e52"),
		"abilities": {
			"basic": {"name": "Nuoli", "desc": "Pidä pohjassa ladataksesi. Paikallaan lataa nopeammin; täysi lataus lävistää.", "cd": 0.5},
			"a1": {"name": "Väistösyöksy", "desc": "Loikkaa taaksepäin ja jättää lähtöpaikkaan piikkialueen, joka hidastaa ja vahingoittaa siihen astuvia.", "cd": 7.0},
			"a2": {"name": "Nuolisade", "desc": "Nuolia sataa valitulle alueelle hetken päästä.", "cd": 8.0},
			"dodge": {"name": "Kuperkeikka", "desc": "Nopea kieräys, joka lataa jousen heti valmiiksi.", "cd": 3.5},
			"ult": {"name": "Läpäisynuoli", "desc": "Tähtää pitämällä ulttinappi pohjassa (pitkä viiva) ja vapauta: todella nopea, pitkän kantaman nuoli joka lävistää kaiken ja tekee valtavaa vahinkoa.", "cd": 0.0},
		},
	},
	"boulder": {
		"name": "Boulder",
		"role": "Tankki",
		"difficulty": 1,
		"hp": 360.0,
		"speed": 285.0,
		"ratings": {"kesto": 5, "liike": 1, "vahinko": 2, "tuki": 3},
		"weapon": "Kivihansikkaat",
		"desc": "Kävelevä kallio. Hallitsee aluetta kestävillä kivimuureilla ja piikkikartioilla; kerää raivoa taistelusta.",
		"color": Color("9aa3ad"),
		"color_b": Color("4f5a66"),
		"abilities": {
			"basic": {"name": "Murskaava isku", "desc": "Raskas lyönti, joka tönäisee kunnolla.", "cd": 0.7},
			"a1": {"name": "Kivimuuri", "desc": "Nostaa kestävän muurin (oma kesto-hp), joka estää liikkeen ja ammukset. 3 latausta — voi pystyttää vaikka kaikki heti, lataukset palautuvat hitaasti. Tähtää pitämällä nappia pohjassa.", "cd": 0.3},
			"a2": {"name": "Piikkikartio", "desc": "Iskee neljä piikkiaaltoa eteenpäin kartioon: aallot levenevät, työntävät kohteet poispäin ja juurruttavat hetkeksi. Kuluttaa raivoa.", "cd": 5.0},
			"dodge": {"name": "Jyräys", "desc": "Raskas loikka eteenpäin.", "cd": 5.0},
			"ult": {"name": "Vyöry", "desc": "Vyöryy voimalla tähtäyssuuntaan kaataen viholliset ja jättää kiviseinän matkan varrelle, joka murenee hetken päästä.", "cd": 0.0},
		},
	},
	"volt": {
		"name": "Volt",
		"role": "Mage",
		"difficulty": 2,
		"hp": 160.0,
		"speed": 325.0,
		"ratings": {"kesto": 2, "liike": 3, "vahinko": 5, "tuki": 1},
		"weapon": "Sähkökelat",
		"desc": "Elävä ukkospilvi. Käyttää manaa — salamoi tiheään kunnes mana loppuu.",
		"color": Color("ffe14a"),
		"color_b": Color("8f7600"),
		"abilities": {
			"basic": {"name": "Kipinä", "desc": "Sähköammus, joka hyppää lähimpään toiseen viholliseen.", "cd": 0.55},
			"a1": {"name": "Ketjusalama", "desc": "Salama, joka ketjuttaa jopa kolmeen viholliseen ja hidastaa.", "cd": 7.0},
			"a2": {"name": "Sähkökenttä", "desc": "Rätisevä alue, joka hidastaa ja tekee vahinkoa.", "cd": 8.0},
			"dodge": {"name": "Kipinähyppy", "desc": "Salamannopea siirtymä.", "cd": 4.0},
			"ult": {"name": "Ukkosmyrsky", "desc": "Salamat iskevät lähivihollisiin sarjana ja tainnuttavat.", "cd": 0.0},
		},
	},
	"maestro": {
		"name": "Maestro",
		"role": "Tuki",
		"difficulty": 2,
		"hp": 195.0,
		"speed": 320.0,
		"ratings": {"kesto": 3, "liike": 3, "vahinko": 2, "tuki": 5},
		"weapon": "Ääniaaltoheitin",
		"desc": "Rytmin mestari. Käyttää manaa — kiihdyttää ja suojaa joukkuetta tiuhaan kunnes mana loppuu, sitten se palautuu.",
		"color": Color("ff6bd0"),
		"color_b": Color("99307d"),
		"abilities": {
			"basic": {"name": "Ääniaalto", "desc": "Työntävä ääniammus.", "cd": 0.5},
			"a1": {"name": "Kiihdytysriffi", "desc": "Lähiliittolaiset saavat vauhtia ja suojakilven.", "cd": 8.0},
			"a2": {"name": "Basso-isku", "desc": "Bassoaalto eteen: työntö ja lyhyt tainnutus.", "cd": 8.0},
			"dodge": {"name": "Tahdinvaihto", "desc": "Nopea sivuliuku.", "cd": 3.5},
			"ult": {"name": "Crescendo", "desc": "Suuri alue: liittolaiset paranevat ja kiihtyvät, viholliset hidastuvat.", "cd": 0.0},
		},
	},
	"shade": {
		"name": "Shade",
		"role": "Assassin",
		"difficulty": 3,
		"hp": 152.0,
		"speed": 350.0,
		"ratings": {"kesto": 1, "liike": 5, "vahinko": 5, "tuki": 1},
		"weapon": "Varjot ja shurikenit",
		"desc": "Savuun katoava kiusankappale. Kaksivaiheiset kyvyt: loikkaa ja palaa varjolle, heitä ja kutsu shuriken takaisin.",
		"color": Color("9089b8"),
		"color_b": Color("3f3a63"),
		"abilities": {
			"basic": {"name": "Varjokiekko", "desc": "Nopea pyörivä heittokiekko.", "cd": 0.45},
			"a1": {"name": "Varjoloikka", "desc": "Tähtää ja loikkaa, jättäen varjon lähtöpaikkaan. Paina uudelleen palataksesi varjolle ja iskeäksesi alueesi.", "cd": 5.0},
			"a2": {"name": "Paluushuriken", "desc": "Tähtää ja heitä iso shuriken; paina uudelleen kutsuaksesi sen takaisin. Osuu molempiin suuntiin, ja kopatessa jäähdytys laskee.", "cd": 4.0},
			"dodge": {"name": "Varjoaskel", "desc": "Nopea väistö, joka lataa ultimatea.", "cd": 3.0},
			"ult": {"name": "Varjoisku", "desc": "Hetken salamannopea; iskut tehostuvat 60 %.", "cd": 0.0},
		},
	},
	"tide": {
		"name": "Tide",
		"role": "Fighter",
		"difficulty": 2,
		"hp": 240.0,
		"speed": 315.0,
		"ratings": {"kesto": 4, "liike": 4, "vahinko": 3, "tuki": 2},
		"weapon": "Vesikeihäs",
		"desc": "Virtaava taistelija. Kerää raivoa taistelusta ja purkaa sen vesikykyihin.",
		"color": Color("4ad4ff"),
		"color_b": Color("176d94"),
		"abilities": {
			"basic": {"name": "Keihäspisto", "desc": "Pitkä ja kapea pisto eteen.", "cd": 0.55},
			"a1": {"name": "Vesivana", "desc": "Syöksy, joka jättää kiihdyttävän vanan. 3 latausta, lyhyt käyttöväli — lataukset palautuvat hitaasti. Ei kuluta raivoa.", "cd": 0.55},
			"a2": {"name": "Aalto", "desc": "Työntävä vesiaalto eteen, joka hidastaa. Kuluttaa raivoa.", "cd": 7.5},
			"dodge": {"name": "Virtaliuku", "desc": "Liukas väistö, joka antaa vauhtia.", "cd": 4.0},
			"ult": {"name": "Vesipatsas", "desc": "Ryntää vedellä eteen (tähtäyssuuntaan), nostaa lähiviholliset vesipatsaan päälle ja iskee heidät alas vahingolla ja tainnutuksella.", "cd": 0.0},
		},
	},
	"scout": {
		"name": "Scout",
		"role": "Ranger",
		"difficulty": 2,
		"hp": 180.0,
		"speed": 330.0,
		"ratings": {"kesto": 2, "liike": 3, "vahinko": 3, "tuki": 4},
		"weapon": "Vaahtopallokivääri",
		"desc": "Joukkueen silmät. Konekivääri isolla lippaalla (lataa kierähtämällä), ja osumat lataavat energiaa merkki- ja tainnutuspalloihin.",
		"color": Color("c9d16b"),
		"color_b": Color("6b7a2f"),
		"abilities": {
			"basic": {"name": "Konekivääri", "desc": "Pidä liipaisin pohjassa ryöpyttääksesi. Iso lipas, pitkä lataus — lataa kesken taistelun kierähtämällä (X).", "cd": 0.1},
			"a1": {"name": "Merkkipanos", "desc": "Pitkän kantaman tarkkuuspanos: merkitty kohde ottaa +45 % vahinkoa kaikilta. Tähtää pitämällä nappia pohjassa.", "cd": 7.0},
			"a2": {"name": "Tainnutuspallo", "desc": "Tähdättävä tahmea pallo, joka pamahtaa ja tainnuttaa pienellä alueella. Tähtää pitämällä nappia pohjassa.", "cd": 9.0},
			"dodge": {"name": "Kierähdys", "desc": "Nopea rullaus, joka lataa lippaan heti täyteen.", "cd": 3.5},
			"ult": {"name": "Merkkisade", "desc": "Merkitsee kaikki lähiviholliset ja kiihdyttää joukkueen.", "cd": 0.0},
		},
	},
	"prism": {
		"name": "Prisma",
		"role": "Tuki",
		"difficulty": 3,
		"hp": 190.0,
		"speed": 315.0,
		"ratings": {"kesto": 2, "liike": 3, "vahinko": 3, "tuki": 5},
		"weapon": "Valoprisma",
		"desc": "Sädetuki. Kanavoi säteitä: toinen vahingoittaa ja hidastaa, toinen parantaa liittolaisia. Käyttää manaa.",
		"color": Color("5be0e0"),
		"color_b": Color("1f7d8c"),
		"abilities": {
			"basic": {"name": "Valonsäde", "desc": "Kevyt valoammus.", "cd": 0.5},
			"a1": {"name": "Polttosäde", "desc": "Pidä pohjassa: jatkuva säde joka hidastaa voimakkaasti ja tekee kohtalaista vahinkoa. Kuluttaa runsaasti manaa.", "cd": 0.0},
			"a2": {"name": "Hoitosäde", "desc": "Pidä pohjassa: jatkuva säde joka parantaa liittolaisia. Kuluttaa manaa.", "cd": 0.0},
			"dodge": {"name": "Valonpyrähdys", "desc": "Nopea väistöliuku.", "cd": 3.5},
			"ult": {"name": "Loistokehä", "desc": "Pidä pohjassa nähdäksesi alue, vapauta: sisällä olevat liittolaiset saavat lisää vahinkoa ja vauhtia.", "cd": 0.0},
		},
	},
	"rift": {
		"name": "Rift",
		"role": "Assassin",
		"difficulty": 3,
		"hp": 120.0,
		"speed": 355.0,
		"ratings": {"kesto": 1, "liike": 5, "vahinko": 5, "tuki": 1},
		"weapon": "Tyhjyyden tikari",
		"desc": "Tyhjyyden salamurhaaja. Perusiskut kasaavat pinoja, jotka räjäytetään; merkitse ja varppaa kohteelle; ultti pysäyttää ajan ympäriltä.",
		"color": Color("9d4edd"),
		"color_b": Color("3a0e5c"),
		"abilities": {
			"basic": {"name": "Tyhjyysviilto", "desc": "Melee-viilto joka kasaa pinon kohteeseen (enintään 5).", "cd": 0.32},
			"a1": {"name": "Merkkiheitto", "desc": "Tähtää pitämällä nappia pohjassa ja vapauta heittääksesi merkin. Jos se osuu (oma tai vihollinen), paina uudelleen varpataksesi kohteelle.", "cd": 8.0},
			"a2": {"name": "Räjäytys", "desc": "Melee-isku joka räjäyttää kohteen pinot: enemmän pinoja = enemmän vahinkoa. Täydet 5 pinoa nollaa jäähdytyksen.", "cd": 6.0},
			"dodge": {"name": "Varjoloikka", "desc": "Nopea tyhjyysloikka.", "cd": 3.0},
			"ult": {"name": "Ajanpysäytys", "desc": "Pysäyttää ajan ympärillä: kaikki muut (myös omat) jäätyvät hetkeksi, sinä liikut ja toimit vapaasti.", "cd": 0.0},
		},
	},
	"titan": {
		"name": "Titaani",
		"role": "Tankki",
		"difficulty": 2,
		"hp": 380.0,
		"speed": 300.0,
		"ratings": {"kesto": 5, "liike": 2, "vahinko": 2, "tuki": 3},
		"weapon": "Rautakourat",
		"desc": "Murskaava jättiläinen. Tekee vähän vahinkoa mutta kestää valtavasti: nappaa vihollisen kiinni ja heittää pois, ja kuluttaa raivoa suojautuakseen ja parantuakseen.",
		"color": Color("c05a3a"),
		"color_b": Color("4a1b12"),
		"abilities": {
			"basic": {"name": "Murskaava isku", "desc": "Raskas lähi-isku. Jokainen osuma lyhentää Tartu ja heitä -kyvyn jäähdytystä.", "cd": 0.6},
			"a1": {"name": "Tartu ja heitä", "desc": "Nappaa edessä olevan vihollisen ja heittää sen tähtäyssuuntaan, jättäen lyhyen tainnutuksen. Raivotilan aikana nostaa kaikki lähiviholliset ilmaan.", "cd": 7.0},
			"a2": {"name": "Raivosuoja", "desc": "Pidä pohjassa: kuluttaa raivoa, vähentää otettua vahinkoa joka suunnasta ja palauttaa elämää.", "cd": 6.0},
			"dodge": {"name": "Syöksyrynnäkkö", "desc": "Raskas syöksy, joka tönäisee ja hidastaa osuessaan.", "cd": 4.5},
			"ult": {"name": "Raivotila", "desc": "Muuttuu hetkeksi berserkiksi: nopeampi liike, iskunopeus ja vahinko nousevat, ja Tartu ja heitä muuttuu alueen ilmaanheitoksi.", "cd": 0.0},
		},
	},
}


static func get_def(id: String) -> Dictionary:
	return HEROES[id]


static func ability(id: String, slot: String) -> Dictionary:
	return HEROES[id]["abilities"][slot]


static func cooldown(id: String, slot: String) -> float:
	return HEROES[id]["abilities"][slot]["cd"]
